[MFA-2681] Add advanced telemetry to SDK
auth0/Guardian.Android pull request #113
Opened 2024-02-06 14:16 UTC by andy317fe301f8c7

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not the default branch

2024-02-06 19:29 UTC, shadow-dahm requested changes
Minor comment, and can we please cover the extra constructors and paths with test cases?

2024-02-21 15:41 UTC, oleksandrozerov-okta commented on guardian/src/main/java/com/auth0/android/guardian/sdk/Guardian.java
> +                builder.setTelemetryInfo(telemetryInfo.appName, telemetryInfo.appVersion);
just cmd+c cmd+v from the `enableLogging` line above, removed `this` to mimic that behaviour

2024-03-14 12:15 UTC, shadow-dahm approved these changes
Extra tests appear to cover, thanks!

2024-03-14 17:58 UTC, oleksandrozerov-okta approved these changes

2024-03-15 14:46 UTC, merged